name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5  # Latest version as of April 2025
      with:
        go-version: '1.20'

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -v -o prompter ./...

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -v -o prompter.exe ./...

    - name: Test
      run: go test -v ./...

    - name: Upload Linux Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prompter-linux-amd64
        path: prompter

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prompter-windows-amd64
        path: prompter.exe
